### PR TITLE
Form preview

### PR DESCRIPTION
**Pull request by yovic4**
Added preview for fanart and video form
image

image

### CODE REVIEW

**Comment by nyxordinal** [comment]
is there a limit to the fanart that can be previewed?
because of the 10 times I tried the preview, about 3 times failed to preview

**Comment by yovic4** [comment]
I tried the link you gave, it seem this more of the problem with the link that with the component. So should leave it as it is, since this can be a warning for the submitter that their link is not usable

**Review by nyxordinal — APPROVED** [review]
ok, just need to resolve the conflict and this PR will be ready to merge

**Comment by yovic4** [comment]
image

add message preview

**Pull request merged**
