### PR TITLE
Tidy up

### LINKED ISSUE #50: Forms check confirm
https://github.com/Kaichou-Project/kaichou-graduation/blob/7b4528c78743ad049d72f83b249accc6d729adef/packages/frontend/components/Forms/CheckConfirm.tsx#L17-L21
Shouldn't we capitalize the letter "I" in "...i have explicit permission..."? I was looking through it and I thought it was kinda odd

### PR DESCRIPTION
**Pull request by yovic4**
Minor fix on some things : 
- Change I capitalization as in #50 
image
- Change soundboard category  to something more presentable
image
- Add `toTheTop` button to fanart and clip page

### CODE REVIEW

**Comment by nyxordinal** [comment]
Some space is still missing there
image

**Comment by yovic4** [comment]
I fixed this bug in #70

**Comment by nyxordinal** [comment]
> I fixed this bug in #70

Ok 👍

**Review by nyxordinal — APPROVED** [review]
Nice work !

**Pull request merged**
