### PR TITLE
Responsive header

### LINKED ISSUE #54: Make header/navigation responsive
image
image

### PR DESCRIPTION
**Pull request by keijeizei**
-make the header, title, and navigation bar responsive
-fix the bug where the title overflows on small screens
-add scss variables `$breakpoint-tablet` and `$breakpoint-phone` which can be used for media query breakpoints of other components
image

### CODE REVIEW

**Comment by azuraga** [comment]
Navigation bar hover text is not centered on mobile. Do you think this can be included in here? (ignore the lack of background since this is Firefox)
image

**Comment by keijeizei** [comment]
May I know what screen width is that? The text on my firefox gets on the bottom instead.
image

**Comment by azuraga** [comment]
The screenshot came from a Samsung Galaxy S20, Firefox

**Review by azuraga — APPROVED** [review]

**Comment by azuraga** [comment]
Thanks for your contribution!

**Pull request merged**
