### PR TITLE
Add SampleHomeBlock component

### PR DESCRIPTION
**Pull request by ArticulateMemory**
Adds a component/page for a sample home block (/SampleHomeBlock to access the component).

Also extends the MessageList and modifies the Message components to fit.

### CODE REVIEW

**Review by RedMaps — CHANGES_REQUESTED** [review]
Please format with eslint and prettier. Instructions in README.md

**Comment by ArticulateMemory** [comment]
It looks like I can't mark this as a draft PR since it's already open... I might close it and reopen it.

**Comment by nyxordinal** [comment]
revert this PR back to draft for you @ElectricAlgorhythm

**Comment by RedMaps** [comment]
Does it make sense to keep this open at all now that the code base has changes so much?

**Comment by ArticulateMemory** [comment]
> Does it make sense to keep this open at all now that the code base has changes so much?

That's why I wanted to change it to a draft, but if you want to close it for now while I catch up that's ok with me.

**Comment by RedMaps** [comment]
If you plan to keep working on this then no, it doesnt make sense to close it ^^

**Comment by ArticulateMemory** [comment]
Since there's already a home page now I'll close it and move onto something else, thanks!

**Pull request closed without merging**
