### PR TITLE
Fanart

### PR DESCRIPTION
**Pull request by yovic4**
image

Made the fanart page. when and image clicked it will be enlarged like this

image

Note:
- this is continuing PR #69 
- The list is already connected to db, so if the page is empty or error, it might be because of the db content. I put some temp fanart file at `/temp-fanart/` for testing. inputing the fanart can already be done in the form

### CODE REVIEW

**Review by nyxordinal — APPROVED** [review]
I dont find any issue with this PR, for now I'll approve this
Maybe @RedMaps has any comment?

**Comment by yovic4** [comment]
Ok thx, but just for a reminder, this is continuing PR #69, so merging this will also merging that PR changes. So hopefully that PR is merged before this one

**Comment by nyxordinal** [comment]
noted 👍

**Comment by yovic4** [comment]
image

For now, I add the form like this. Already work with the new backend I think

**Comment by nyxordinal** [comment]
It seems this PR has no other issue so I'll merge this
Thank you for your contribution 👍 @yovic4

**Pull request merged**
