### PR TITLE
Working progress bar

### LINKED ISSUE #25: Make progress bar on sound player work.
The audio players for the soundboard should display the current clip position at the bottom.

image

### PR DESCRIPTION
**Pull request by yovic4**
image
I make the progress bar move based on the duration

### CODE REVIEW

**Comment by yovic4** [comment]
image
Also added the new footer to the page

**Comment by RedMaps** [comment]
Can you have the text centered without taking the progress bar into account like this?

image

**Comment by yovic4** [comment]
image

This should fix that

**Review by RedMaps — APPROVED** [review]
Flawless, thanks for the improvement!

**Pull request merged**
