### PR TITLE
Implement form create API

### LINKED ISSUE #78: Adding Title Property in Video Model
There is a need to store the video title in the DB, basically what will have to do is :
* add new property `title` in Video Model in Backend
* add new input in Video/Clip submission form in Frontend

### PR DESCRIPTION
**Pull request by yovic4**
Implementation for create fanart and video API. The implementation is exactly the same way as in #49

### CODE REVIEW

**Comment by nyxordinal** [comment]
Looks good to me, my suggestion on action after successful creation is to show success notification

**Comment by yovic4** [comment]
image

Make success notification like this. The "submit another message" button will hard refresh the page

**Comment by nyxordinal** [comment]
image
When I successfully send fanart or video/clip, one of the buttons in the popup notification still shows `Submit another message` instead of something like `Submit another fanart`
is it supposed to be like that?

**Comment by yovic4** [comment]
Yeah, I was thinking that the title for all form is the same `Submit a Message`, so I was thinking I can get away with this one too lol. Do you want all form to have different button?

**Comment by nyxordinal** [comment]
if it's not too much of a hassle, could you please make all form to have different button?
just need to change on that button

**Comment by yovic4** [comment]
image

done

**Comment by azuraga** [comment]
Looks good, but there's a lot of duplicate code in the three submission types. Would there be a better way to structure this?

**Comment by yovic4** [comment]
I feel like it is better to make it like this for now to allow customization across different forms since there might be changes to individual form. Like for example message will have that languages feature and video will have  title, so even though it seem all the same now, it might diverge late on

**Comment by nyxordinal** [comment]
Since we will need title for the video/clips, could you add new input in video submission form for the title?

**Comment by yovic4** [comment]
Yeah, should be easy to do that.

However, has this been finalized? Cause in discord there also seem to be a discussion on using youtube api for getting the title

**Comment by yovic4** [comment]
image

For now, I add the form like this. Already work with the new backend I think

**Review by nyxordinal — APPROVED** [review]
Good job, as always thanks for your contribution !

**Pull request merged**
