### PR TITLE
Add footer

### LINKED ISSUE #17: Add Footer
Screenshot 2021-06-16 at 17 21 43

### PR DESCRIPTION
**Pull request by keijeizei**
Add the footer component.

Also added some basic scss with structure and colors. The styles are not yet responsive to screen sizes. I will let the more experienced designers handle this.

### CODE REVIEW

**Comment by RedMaps** [comment]
The code looks fine though the footer doesn't yet exactly look like the one in the design since there's some space on the right and the back polygon is rounded. If you can fix that thats good, otherwise ill try and open a PR to your fork with a few fixed tomorrow. As always thanks for your contribution! 👍 

*Edit: Screenshot for reference*

image

**Comment by keijeizei** [comment]
I think I fixed the footer spacing and the polygon shape for most screen sizes. Let me know if there are other things to be adjusted.

**Comment by nyxordinal** [comment]
Looks good for me

**Review by RedMaps — APPROVED** [review]
This looks really good now! Ill open another issue to add the links to the footer

**Pull request merged**
