### PR TITLE
More Message Board Boilerplate

### PR DESCRIPTION
**Pull request by Mecki-Messer**
i added files to start working on video and image support.
Stubs are in place, video already has boilerplates
also refactored code to reflect the naming conventions used in the ERD

its basically a whole bunch of added files and stubs

leaving this here in case anyone wants to work with it while i sleep

### CODE REVIEW

**Comment by Mecki-Messer** [comment]
suggestions are also very much welcome, im not really sure if this is the right way to go about things

**Comment by ArticulateMemory** [comment]
This will conflict a bit with #10; I'll just have to rebase or something, no worries.

**Comment by Mecki-Messer** [comment]
> 
> 
> This will conflict a bit with #10;

yeah, i thought so as soon as i saw it. well sort it out, your way of doing things will be better as far as i can tell

**Comment by Mecki-Messer** [comment]
ill close this since it is heavily conflicting with other stuff

**Pull request closed without merging**
