### PR TITLE
Responsive ToTheTop button and soundboard

### PR DESCRIPTION
**Pull request by keijeizei**
-Quick media queries to make the ToTheTop button and soundboard responsive
-Add new colors to `variables.scss` (`$gray` and `$dark-gray`)
Before:
image
image
After:
image
image

### CODE REVIEW

**Comment by nyxordinal** [comment]
I found no problem in this PR, for now I will approve this @RedMaps

**Review by nyxordinal — APPROVED** [review]
I found no problem in this PR, for now I will approve this @RedMaps

**Comment by nyxordinal** [comment]
@keijeizei could you please merge this PR with the latest commit from main branch ? and check again the responsiveness?

**Comment by keijeizei** [comment]
Everything still works fine! @nyxordinal

**Review by azuraga — APPROVED** [review]

**Comment by azuraga** [comment]
Merging this now. Thanks for your contribution!

**Pull request merged**
