### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by yovic4**
image

Putting some foundation for video carousel at main page. Will continue after `VideoCard` finished

Also planning on making the "messages from community" board

### CODE REVIEW

**Comment by yovic4** [comment]
image

Integrate the video player for the carousel at home page

Also putting some foundation for the board at main page. Will continue after MessageCard FanartCard finished

**Comment by yovic4** [comment]
Mostly done, but still lacking few things: 
- the message card is just a dummy, since it is not done
- not sure how to get and sort these items (especially the messages and fanarts)
image

But should be good enough to be reviewed to speed up the process

**Comment by yovic4** [comment]
Note : I also change the name `clip` to `video` for consistency

**Comment by nyxordinal** [comment]
I have no comments on this PR, just need to figure out how to sort between messages and fanart on the home page

**Comment by yovic4** [comment]
Added a randomization to the order, but i have some commented code for time based ordering

**Comment by nyxordinal** [comment]
> Added a randomization to the order, but i have some commented code for time based ordering

You can uncomment the time ordering code, I already check in local machine. Its work as expected
Nice work !

**Comment by yovic4** [comment]
Removed the time based sorting since we use the random one

**Review by nyxordinal — APPROVED** [review]

**Comment by yovic4** [comment]
image

integrate messageCard to home

**Pull request merged**
