### PR TITLE
Responsive footer

### LINKED ISSUE #39: Make footer responsive
image
image
The footer isn't responsive yet. I'll be the one doing this.

### PR DESCRIPTION
**Pull request by josef-yu**
Closes #39  

-Added SCSS variable $breakpoint-lgphone to be used for media queries
-Made the link columns responsive
-Made the copyright text responsive
-Made the social image links responsive

image
image
image
image
image

### CODE REVIEW

**Review by nyxordinal — APPROVED** [review]
Looks good for me !

**Comment by nyxordinal** [comment]
Hi! Could you please merge the latest commits in the main branch into this PR and make sure everything still happens as expected?
If no other issues occur, we'll proceed to merge this PR

**Comment by azuraga** [comment]
How much of a difference would it make to just use `breakpoint-phone` instead of `breakphone-lgphone`? Apart from that, great job!

**Comment by josef-yu** [comment]
It is at `$breakpoint-lgphone` that the columns will start to overlap with the others, so it was really needed to make a breakpoint at that width.

**Comment by azuraga** [comment]
Alright, I guess that works for now. Will be merging!

**Pull request merged**
