### PR TITLE
Prepare for Second Deploy

### PR DESCRIPTION
**Pull request by nyxordinal**
Implement (pick) changes from previous deploy freeze PR #82 
* add express-rate-limiter middleware
* add cert and privkey for dev
* add dev and prod mode in backend (must set additional env variabel in `backend/.env`
* remove captcha
* remove check confirm from FormMessage and FormVideo
* removed video metadata fields (they have to be checked for correctness anyways, might as well fill with API/manually)
* update message in success popup
* append `/create` in API endpoint for creation
* rename Clip to Video for consistency in some part of frontend

### CODE REVIEW

**Review by azuraga — COMMENTED** [review]
The instances of `POST /x` haven't been changed to `POST /create/x`. The rest seems to work properly.

**Comment by azuraga** [comment]
> rename Clip to Video for consistency in some part of frontend

Does this mean that all mentions of 'Clip' have been changed to 'Video'? Since I saw still some 'Clip's, e.g. in the navigation bar

**Comment by nyxordinal** [comment]
Ah missed that one

**Review by azuraga — APPROVED** [review]
Seems fine to me.

**Pull request merged**
